### PR TITLE
Release/2.18.0

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Release 2.18.0

No major UI changes

Mostly deploying GH action updates, removing old AWS build steps
Plus minor dependency updates

### CODE REVIEW

**Comment by alfetopito** [comment]
@SocketSecurity ignore playwright@1.30.0
@SocketSecurity ignore @sentry/cli@1.74.6
@SocketSecurity ignore @fortawesome/fontawesome-common-types@6.3.0
@SocketSecurity ignore @fortawesome/fontawesome-svg-core@6.3.0
@SocketSecurity ignore @fortawesome/free-regular-svg-icons@6.1.2

**Comment by alfetopito** [comment]
@SocketSecurity ignore @fortawesome/free-solid-svg-icons@6.1.2

**Comment by alfetopito** [comment]
Merging to deploy to barn for testing

Please post merge review

**Comment by elena-zh** [comment]
LGTM

**Pull request merged**
