### PR TITLE
[Batch Viewer] Show the receiver

### LINKED ISSUE #106: [batch viewer] Show the receiver
**Description**
Show the receiver of the tokens in the batch viewer

The receiver of the trade is not currently shown.
 I would help to understand the batches if that information is displayed

Consider this example for tx https://etherscan.io/tx/0x0d6f18a97690de9d70cdfe00231ee6baf722a12669f3260fb1faf3d2e25dca38

There's only one seller with address `0x84e5c8518c248de590d5302fd7c32d2ae6b0123c`, which dumps a lot of tokens for WETH. The WETH will be sent to `0xa03be496e67ec29bc62f01a428683d7f9c204930`

As you see in https://explorer.cow.fi/tx/0x0d6f18a97690de9d70cdfe00231ee6baf722a12669f3260fb1faf3d2e25dca38?tab=graph  we represent the WETH arriving to the settlement contract but not arriving to the receiver

image

### PR DESCRIPTION
**Pull request by matextrem**
# Summary

Closes #106 

Added receiver when it's different from the order's owner.

Screen Shot 2022-06-14 at 10 02 20

# To Test

1. Open any tx with receivers and go to batch viewer tab. (i.e `tx/0x0d6f18a97690de9d70cdfe00231ee6baf722a12669f3260fb1faf3d2e25dca38`
* You will see the receiver grouped along with the owner of each order.

Example tx
Fix: https://pr120--explorer.review.gnosisdev.com/tx/0x0d6f18a97690de9d70cdfe00231ee6baf722a12669f3260fb1faf3d2e25dca38?tab=graph

Old: https://explorer.cow.fi/tx/0x0d6f18a97690de9d70cdfe00231ee6baf722a12669f3260fb1faf3d2e25dca38?tab=graph

### CODE REVIEW

**Comment by matextrem** [comment]
@ramirotw I noticed the same but I thought it was due to barn/prod not being integrated since I got it even before starting developing this feature. 

@elena-zh each group node needs a unique id to be differentiated from each other. How should we proceed in this case ?

**Comment by elena-zh** [comment]
@matextrem , unfortunately, I'm not a tech specialist to solve these tech  issues you are asking me. 
While testing this or that feature, I'm proposing some enhancements how this or that thing could look better for an end user. 
You can simply answer me that this or that is impossible to implement due some kind of limitations. 

@ramirotw , could you please help me to answer Mati's question? 

Thanks

**Comment by elena-zh** [comment]
Do we need to show 2 the same addresses in the group when Sender and Receiver is the same account?
image

**Comment by ramirotw** [comment]
> As an enhancement, maybe we could show all orders inside the CowProtocol as a batch diagram when click on the group block?
> 
> image
> 
> @ramirotw , @alfetopito , @alongoni , WDYT?

I'm pretty sure I didn't understand the enhancement you proposed @elena-zh

**Comment by ramirotw** [comment]
> And for the arrow coming from the Cow explorer node to the receiver, it does not exists in the transfers coming from tenderly API. Should I create it manually ?

The Transfers' events are in the Tenderly response 
image

**Comment by elena-zh** [comment]
> > As an enhancement, maybe we could show all orders inside the CowProtocol as a batch diagram when click on the group block?
> > image
> > @ramirotw , @alfetopito , @alongoni , WDYT?
> 
> I'm pretty sure I didn't understand the enhancement you proposed @elena-zh

@ramirotw , I mean not to completely hide CoW Protocol transactions in 1-2 arrows
image
but have a possibility to see all transactions by clicking on the group area (expand/open in an additional modal/etc.)
image

Thanks

**Comment by matextrem** [comment]
> > And for the arrow coming from the Cow explorer node to the receiver, it does not exists in the transfers coming from tenderly API. Should I create it manually ?
> 
> The Transfers' events are in the Tenderly response image
> 
> image
> 
> @matextrem ☝️

I think those transfers represents the one going from the Cow explorer to the settlement contract (receiver), but not from the cow explorer to the receiver as a trader. If I use it to draw that line, the first edge is removed (See images below)
Screen Shot 2022-06-16 at 00 43 40

Screen Shot 2022-06-16 at 00 44 05


So I'm a bit confused at this point

**Review by ramirotw — APPROVED** [review]
nice!

image

**Comment by elena-zh** [comment]
Nice changes. 
The only thing is that I noticed that there is no arrows for 1 node in [this ](https://pr120--explorer.review.gnosisdev.com/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/?tab=graph) transaction: 
no arrow

**Comment by matextrem** [comment]
@elena-zh Fixed!

**Review by elena-zh — APPROVED** [review]
Hey @matextrem , LGTM now!

I have found another edge case related to overlapping receiver node other elements, so I created a separate issue #131 if you want to fix it later. 

Thanks

**Review by alfetopito — APPROVED** [review]

**Pull request merged**
