### PR TITLE
Release v2.12.0

### PR DESCRIPTION
**Pull request by henrypalacios**
# Release v2.12.0

:red_circle: DON'T SQUASH :red_circle:

## Main Feature
- Add support for **Görli** test network
- Soft launch of the **Appdata** page
- Improvements and bug fixes: 
    - Improvement in the status label when an order is **partially filled** on the transaction page, user orders page, in addition to the order detail page.
    - Fixes to the amount displayed on order execution, the total amount paid is now reported.

## Change Log
4c238452 Hardcode zero address for ipfs fetching (#194)
5b763cf6 183/fix filled amount issues 2 (#192)
dd829b8d Adding tag partial fill when order is partially filled (#172)
6c7e19c5 Merge pull request #168 from cowprotocol/160/metadata-page, Add Metadata page(#168)
16387098 add goerli and use latest SDK changes (#182)
5d5e73ad Fix issue with executed amounts (#161)

## Dependency Updates
c0291ff6 Bump Version to 2.12.0

### CODE REVIEW

**Comment by elena-zh** [comment]
Hi there!
I would not include #161 PR into the release until the #184 PR is merged (it fixes an issue with Buy order amounts that was introduced in #161 PR).

**Review by elena-zh — CHANGES_REQUESTED** [review]
I have found an issue with Tx search: when I search for a Gorli TX ( example `0xae6fe6be6d795ffd304374f81e4c47cdb8e4a7ee49c37f15a271cf6ee0d3e7e1`) from Mainnet/Rinkeby, I can't load its amounts. 
image

**Comment by elena-zh** [comment]
As for the AppData page, it would be great to change URL param to correspond to the tab name
image

**Comment by elena-zh** [comment]
Besides, I have created several related issues related to the current RC: 
 - https://github.com/cowprotocol/explorer/issues/190
 - https://github.com/cowprotocol/explorer/issues/191
 - updated  https://github.com/cowprotocol/explorer/issues/176

**Comment by elena-zh** [comment]
> `0x5e66bab3ec9f3283527c06944d4322687c66e53d3e2af94843cecf9e8aa9a05a`

Weird, but I can't reproduce the issue now.

**Comment by henrypalacios** [comment]
@elena-zh I have added a commit with a suggestion from Agustin to increase `font-size` just when the tag label in on the **right** to achieve a more proportional alignment.
image

**Review by ramirotw — APPROVED** [review]

**Review by alfetopito — APPROVED** [review]
Code looks good, and I have 2 minor issues with the behaviour.

There's a NaN% in the landing page
Screen Shot 2022-08-22 at 11 02 17

This is hidden so no need to address for the release.
In lager screens, the generated appData expands outside of the container area
Screen Shot 2022-08-22 at 11 07 45


https://user-images.githubusercontent.com/43217/185897265-b6846435-9a34-494a-a049-113d8ffbd802.mov

**Comment by elena-zh** [comment]
> @elena-zh I have added a [commit](https://github.com/cowprotocol/explorer/pull/189/commits/19b0f8c861a8717923dc42567b48f30f64a5c76d) with a suggestion from Agustin to increase `font-size` just when the tag label in on the **right** to achieve a more proportional alignment. image

Hey @henrypalacios , @alongoni  with an increased font-size, the 2nd part still looks shifted to me towards the 1st part 
image

But let not waist time on fixing that. I will create a low-low prio issue for this to address this issue a bit later if requested.

**Comment by elena-zh** [comment]
@alfetopito , 

> This is hidden so no need to address for the release.

Just to let you know, we have an opened issue for this #193

**Review by elena-zh — APPROVED** [review]
Changes LGTM!

I have created a separate issue for 'NAN' #196  that @alfetopito has reported above, as it is not related to the current PR, and is reproducible in Dev environment. 
I vote for fixing it in a separate PR before the release as it is not reproducible in BARN/Staging/Prod. 

Also I created some related issues that might be addressed a bit later.

**Comment by elena-zh** [comment]
Changes LGTM!

**Pull request merged**
