### PR TITLE
136 add goerli 2

### LINKED ISSUE #136: Add Goerli network
**Description**
- Add goerli network to cow-sdk instance constants (Update cow-sdk library)
- Add the option in the network-list menu in the header UI
Selection_615

- Create and verify new route prefix network `/goerli` 
- Enable/check routes for `/goerli` suffixes such as `/search`, `/address`, `/orders`, `/tx`
- Fill in the home page data from the `goerli` network **subgraph**.

### PR DESCRIPTION
**Pull request by alfetopito**
# Summary

Closes #136 

Based on/supersedes https://github.com/cowprotocol/explorer/pull/170/

Rebased against latest `develop` because I needed changes there, so have diverged from original.
You can see what changes have been added by looking from this commit onwards https://github.com/cowprotocol/explorer/pull/182/commits/299f47568e76d4d5c252e786af4923db7871eca6

# Fixes

- [x] AppData loading on order details
- [x] Multi env queries (prod on barn and vice versa)
- [x] Contract address for goerli

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alfetopito , changes LGTM!
However, I still see that environments are mixed up: I see orders placed in Prod/Staging in the PR link, and do not see them when I place orders from Barn/Dev/pr
image

Could you please fix it? 

Thanks!

**Comment by ramirotw** [comment]
> Hey @alfetopito , changes LGTM! However, I still see that environments are mixed up: I see orders placed in Prod/Staging in the PR link, and do not see them when I place orders from Barn/Dev/pr image
> 
> Could you please fix it?
> 
> Thanks!

@elena-zh wasn't the `User Details` orders locked to prod-only orders in purpose? I couldn't find the issue in the sdk to handle this case where we merge paginated responses from the api so I created a new one (https://github.com/cowprotocol/cow-sdk/issues/72).

**Comment by elena-zh** [comment]
@alfetopito , User details show orders from Prod/Staging in 
 - https://explorer.cow.fi/
 - https://protocol-explorer.staging.gnosisdev.com/

And orders from Barn/Dev/PR in
 - https://protocol-explorer.dev.gnosisdev.com/
 - https://barn.cowswap.exchange/#/swap?chain=rinkeby
 - Explorer PR links

I have retested it now, and it works like I describe in https://explorer.cow.fi/ and in   https://protocol-explorer.dev.gnosisdev.com/: https://watch.screencastify.com/v/hjxqD3d1q0PN95Xx34H0 .  

But in the current PR I see orders from Prod/Staging, and completely to not see orders from Barn/Dev/PR
image

I do not know why it happens either, but if it works differently that we currently have in stable environments, I report this. 

As for pagination issue, we decided not to show all orders from Prod and Barn in user details page, and show orders like it is currently works in the 1st part of my message.

**Comment by alfetopito** [comment]
> @alfetopito , User details show orders from Prod/Staging in
> 
>     * https://explorer.cow.fi/
> 
>     * https://protocol-explorer.staging.gnosisdev.com/
> 
> 
> And orders from Barn/Dev/PR in
> 
>     * https://protocol-explorer.dev.gnosisdev.com/
> 
>     * https://barn.cowswap.exchange/#/swap?chain=rinkeby
> 
>     * Explorer PR links
> 
> 
> I have retested it now, and it works like I describe in https://explorer.cow.fi/ and in https://protocol-explorer.dev.gnosisdev.com/: https://watch.screencastify.com/v/hjxqD3d1q0PN95Xx34H0 .
> 
> But in the current PR I see orders from Prod/Staging, and completely to not see orders from Barn/Dev/PR image
> 
> I do not know why it happens either, but if it works differently that we currently have in stable environments, I report this.
> 
> As for pagination issue, we decided not to show all orders from Prod and Barn in user details page, and show orders like it is currently works and I have described in the 1st part of my message.

You are right to point this out Elena.

Without looking into this very deeply, I assume that what is happening is this:
1. On the SDK, we now default to querying PROD, unless otherwise specified with a parameter
2. Since we are not querying both envs for paginated queries, it'll only call PROD
3. Probably (haven't checked the code yet) the query for user orders does not have the env parameter set, thus it's always querying PROD

**Comment by alfetopito** [comment]
> wasn't the User Details orders locked to prod-only orders on purpose?

And replying to Ramiro, user details should reflect the environment we are at, as I don't recall we decided to make it PROD only.

Thus, barn should show barn orders (same for local and PRs) while the rest should show prod orders

**Comment by ramirotw** [comment]
@elena-zh @alfetopito nice catch both! When I refactored the code I didn't include the prod/barn switch for user orders, so it was always defaulting to prod. Now it should work as before.

**Review by ramirotw — APPROVED** [review]

**Pull request merged**
