### PR TITLE
[Batch Viewer] Zoom and drag improvements

### LINKED ISSUE #42: Issues with zooming/dragging and dropping elements on a Batch viewer diagram
Related to [gnosis/gp-ui/#1061](https://github.com/gnosis/gp-ui/pull/1061)

Open https://pr1061--gpui.review.gnosisdev.com/tx/0xc2eb04b549d68c770062591e2561c5b1534ea665c6179d33a779c52376c9161d/

1. Drag the center of the diagram (or any its element) outside the batch viewer area and drop it there
**AR**: the element stays outside the area, and it is impossible to select it/move anywhere else unless you refresh the page: https://watch.screencastify.com/v/qw1ZJeLLR4GXubPt3h8i
**ER**: it would be nice not to allow to drop a diagram area outside the natch viewer area

2. Cow icons stop to be displayed when drag the diagram. See the video: https://watch.screencastify.com/v/yaePSIrC4DQthhd2gBJw
**ER**: it would be nice to keep them always visible. 

3. It would be nice not to allow to overlap elements (drop one element above the other one)
image

> Original issue https://github.com/gnosis/gp-ui/issues/1074 by @elena-zh

### PR DESCRIPTION
**Pull request by alongoni**
# Summary

Closes #42 

# To Test

1. <<Step one>> Open the [batch viewer](https://pr103--explorer.review.gnosisdev.com/tx/0xc2eb04b549d68c770062591e2561c5b1534ea665c6179d33a779c52376c9161d?tab=graph)

### CODE REVIEW

**Comment by ramirotw** [comment]
thanks for the video!

**Comment by alongoni** [comment]
regarding point 1)
image
This will be mitigated by the addition of the reset button (#100). I think if we don't allow moving the nodes outside the BV area, it could cause a conflict with the zoom. WDYT @ramirotw @henrypalacios @elena-zh

**Comment by henrypalacios** [comment]
I tried something to deal with this but it doesn't work so well. It effectively causes a conflict with the zoom :laughing: 

@alongoni while I was trying to build something I came across this [**cytoscape-automove**](https://github.com/cytoscape/cytoscape.js-automove), it could be used to solved that point.

I think we should move on and leave it as a low priority.

**Review by ramirotw — APPROVED** [review]
> This will be mitigated by the addition of the reset button (https://github.com/cowprotocol/explorer/pull/100). I think if we don't allow moving the nodes outside the BV area, it could cause a conflict with the zoom. WDYT @ramirotw @henrypalacios @elena-zh

Agreed @alongoni. 

Nice work!

**Review by matextrem — APPROVED** [review]

**Review by henrypalacios — APPROVED** [review]

**Comment by elena-zh** [comment]
Looks good to me even with elements outside the frame, due to now we have a Reset button that can return the diagram to the default state.

**Pull request merged**
