### PR TITLE
Integrate Tokens table data from Coingecko

### PR DESCRIPTION
**Pull request by ramirotw**
# Summary

WIP

image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @ramirotw , I have done a quick round of tests, and here my list of issues and proposals: 
1. When the table is loaded, [some data appears faster than other one](https://watch.screencastify.com/v/Tj3C6jxb0PvWq6GA0WQ6). Could we show the table 'skeleton' effect until all data is loaded? 
2. AFAIK, the table data should be sorted by 24h volume desc, but it does not seems to be sorted this way:
sorting
3. The table lines are hanging loading when I search for tokens that do not present on the current page: 
search
4. When I change a network to Rinkeby and GC, the table has an infinite loading effect
change network
5. Seems like search by a token address is not working: I tried searching for USDC coin (it is in the list), but search did not return me any results
token address
6. It would be great to left-align # in a mobile view 
number


Enhancements (maybe for next iterations): 
1. Show full amounts on hover like we do for Orders/Transactions tables
image
image

2. Make tokens names or symbols clickable + add a copy icon to them (as we do in Order details /Order list pages
image
image

Thanks!

**Comment by ramirotw** [comment]
Thank you so much for the feedback @elena-zh! I'll fix the issues and add the suggestions that are really helpful for the user.

Btw, the table is sorted by total volume not the 24hs volume

> 2\. AFAIK, the table data should be sorted by 24h volume desc, but it does not seems to be sorted this way:
>     sorting

**Comment by elena-zh** [comment]
@ramirotw , thank for letting me know about the default sorting!

So then maybe we could show this column as well, WDYT?

**Comment by ramirotw** [comment]
We definitely could, it wasn't part of the original design though.

Bringing in @alfetopito @anxolin into the discussion.

**Comment by alfetopito** [comment]
> We definitely could, it wasn't part of the original design though.
> 
> Bringing in @alfetopito @anxolin into the discussion.

Maybe we should show that, yeah.
In fact, we should review what columns to display. Right now I was a bit confused with them:
1. There's a price column, followed by 24h and 7d. Are those related to the price?
2. Then there's the 24h volume. Now I'm wondering, are the previous 2 columns related to the volume instead?
3. Then the last one there's a graph. Is that the price or volume?

I know I can easily look up in the code which is which, but you get my point.

I'll raise this internally

**Comment by alfetopito** [comment]
Regarding the columns, 2 options.

1. Change the sorting to be based on 24h volume instead of total volume. No need to change the column
2. Keep the sorting as is and add total volume column after 24h volume

Only reason to not go with `1` is if it's too hard/complicated to get that query from the subgraph.
If that's the case let's go with `2`, otherwise `1`.

**Comment by ramirotw** [comment]
Not relevant anymore

**Pull request closed without merging**
