### PR TITLE
Update SDK + Update Subgraph API URLs

### PR DESCRIPTION
**Pull request by anxolin**
# Summary

Updates the SDK to the latest version

EDIT:  Also changed the env vars to include the new URLs:
https://subgraph.barn.cow.fi/cow
https://subgraph.barn.cow.fi/cow-goerli
https://subgraph.barn.cow.fi/cow-gc

For now we don't have production URLs, these will be used in staging and production

# To Test

~I wouldn't QA test this one, but the follow up where I will add some new URLs for TheGraph~

Adding QA since I added the env vars to use the new endpoints.

Regarding the new URLs, I see we are not getting the right value of volumes and prices for the different tokens in Goerli and Gnosis Chain!  I think this has to do with the deployment! we need to verify the price oracle (probably there's an issue with Uniswap price oracle in the decentralised version for those networks)

Therefore, for the tests, please let's focus on verifying that other things work:
- Mainnet: everything
- Goerli, GC: everything that is not related to price and volume

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
Dependabot had already bumped to the latest, but it's good to pin to it explicitly anyway

image

**Review by shoom3301 — APPROVED** [review]

**Review by alfetopito — CHANGES_REQUESTED** [review]
Goerli data is coming from GC

Is the env var correct?

image

**Comment by elena-zh** [comment]
Hey @anxolin , I'm still testing, but I have decided to report this issue ASAP: there is disrepancy in volumes (daily, weekly, monthly and yearly) in volumes (compared Barn and the current PR): 
volume

and  native token trades is missing (might be a reason that causes the 1st issue): 
eth

**Review by elena-zh — CHANGES_REQUESTED** [review]
No more issues besides reported ones above by me and @alfetopito (I can also see GC data in Gorli network)

**Comment by anxolin** [comment]
> Goerli data is coming from GC

@alfetopito fixed, it was wrong the env

> Hey @anxolin , I'm still testing, but I have decided to report this issue ASAP: there is discrepancy in volumes (daily, weekly, monthly and yearly) in volumes (compared Barn and the current PR):

Okay, I think this should be left out of this release, should wait until someone has capacity 
cc/ @tukantje

**Comment by elena-zh** [comment]
Now the data in GC and Goerli (besides volumes and prices) corresponds to the data on Prod. 

Issue with ETH token and not matching volumes with Prod is still here (not fixed as mentioned in the comment above).

**Comment by shoom3301** [comment]
SDK is already up to day, the PR is not relevant

**Pull request closed without merging**
