### PR TITLE
Fix long token address in table

### PR DESCRIPTION
**Pull request by fairlighteth**
# Summary

- Addresses https://github.com/cowprotocol/explorer/issues/312

### CODE REVIEW

**Review by alfetopito — COMMENTED** [review]
Not very happy with the result

While some look much better (lido on row 7 uses 2 instead of 3 rows), I do not like the fact that the symbols are broken (USDC, USDT, Ether)

## Left, this change; right, current on `dev`
Screenshot 2023-01-12 at 15 10 16

**Review by anxolin — COMMENTED** [review]
Why not using the css ellipsis here too (`text-overflow`)?

**Comment by fairlighteth** [comment]
@alfetopito Thank you for reviewing. I just pushed a fix for this:

Screenshot 2023-01-12 at 17 36 16

**Review by elena-zh — COMMENTED** [review]
Hey @fairlighteth , the long name looks much better now!
However, I don't think that it looks good in a mobile version: 
image
Would it be better to crop the address in the mddle/in the end like we do for user details address, WDYT?
image

**Review by alfetopito — APPROVED** [review]

**Comment by fairlighteth** [comment]
@elena-zh Good idea on abbreviating! I pushed an update for this. I couldn't test it as the MKR token wasn't showing up for me anymore.

**Review by elena-zh — APPROVED** [review]
Het @fairlighteth , thank you! I'm approving the current changes in order not to block the deployment as I also can't verify the issue (Maker is no longer displayed in the list). 
But I will keep my eye on it.

**Pull request merged**
