### PR TITLE
Release v2.13.0

### PR DESCRIPTION
**Pull request by henrypalacios**
# Release v2.13.0

🚨🚨  DON'T SQUASH 🚨🚨

## Main Features 
- A more flexible menu is incorporated in the [**Home page**](https://protocol-explorer.dev.gnosisdev.com/) along the same lines as [swap.cow.fi](https://swap.cow.fi) 🐮
- Improved usability of the [`/appdata`](https://protocol-explorer.dev.gnosisdev.com/appdata?tab=encode) page such as clear descriptions, user experience, to handle JSON meta data for CoW Protocol orders.
- More granularity has been added to the weekly price **chart** 📈  displayed on the  [**Home page**](https://protocol-explorer.dev.gnosisdev.com/) 
    
 ## Change Log
dd0c91bd Bump version to 2.13.0
66b62c0d New Menu (#186)
7f5cadde change position: fixed -> sticky (#209)
3cdced4e [App Data] Add more context (#204)
5051af52 [Tokens Table] Change query to use tokenHourlyTotals for tokens table (#211)
5b87f765 remove unused values (#203)
2b496c40 [AppData] Store data when switching beetween tabs (#202)
3e34d03f [Top Tokens Table] Rename some columns (#197)
f14f6885 map explorer->api envs explicitly (#201)
5aaf119f Merge pull request #198 from cowprotocol/main

### CODE REVIEW

**Comment by alfetopito** [comment]
2 things about the menu:

1. Not aligned on FF and Safari (ok on Chrome)
Screen Shot 2022-09-15 at 11 26 28

2. The menu arrow rotation is not centered

https://user-images.githubusercontent.com/43217/190369478-4b9098ea-74d6-455c-9177-f3f47893feb6.mov

**Comment by alongoni** [comment]
> 2. The menu arrow rotation is not centered
> 
>  Screen.Recording.2022-09-15.at.11.24.43.mov

Thanks @alfetopito. [Here in storybook](https://pr214--explorer.review.gnosisdev.com/storybook/?path=/story/common-menu--main-menu) it's working properly for me in FF and Chrome. I'll take a look.

**Comment by elena-zh** [comment]
I have reviewed the PR and here are issues I found (besides reported but @alfetopito above): 
 - https://github.com/cowprotocol/explorer/issues/217 - issue I reported above, related to the font param for buttons in Explorer (not only for menu button)
 - https://github.com/cowprotocol/explorer/issues/216 - I think, it will be easy to fix
 - https://github.com/cowprotocol/explorer/issues/215 - low priority, but would great to take a look at it in the next iteration, I think.

**Review by elena-zh — APPROVED** [review]
LGTM with some issues I reported above.

**Review by ramirotw — APPROVED** [review]

**Review by anxolin — COMMENTED** [review]
The menu looks great. 

Happy to deploy this one, but we need to address a few minor issues.

image

This phrase sounds a bit weird. I'm not the best to make a suggestion here, but I will try to suggest something.

```
The appData it's an optional field part of CoW Protocol orders. It allows users/dapps/wallets to attach meta-information to orders. This is useful for giving context to your orders, like crediting the order to a specific UI, adding affiliate information, or even signalling your order should be treated in a special way.  

This field is the hexadecimal digest of an IPFS document’s CID of a JSON file.

The JSON file follows a JSON schema defined on app-data[repo.](https://github.com/cowprotocol/app-data)
```

Also, the link to Dune is old. It returns a 404. I see its also bad in CoW Swap.
If possible, could you update in CoW Swap and cow-fi too?
Good one is https://dune.com/cowprotocol/Gnosis-Protocol-V2

**Comment by elena-zh** [comment]
New changes LGTM!

**Comment by nenadV91** [comment]
Did a post merge review but LGTM :+1:

**Pull request merged**
