### PR TITLE
Hotfix/2.16.1

### PR DESCRIPTION
**Pull request by anxolin**
Shows the fee for Limit Orders

#265

### CODE REVIEW

**Review by elena-zh — COMMENTED** [review]
Hey, I still can see a discrepancy between amount for Filled column for a [Buy ](https://pr267--explorer.review.gnosisdev.com/gc/orders/0xb371dc615c5dcc8da413e16a3110a2151a163707e09df0cb88755cb4ffaf66939fa3c00a92ec5f96b1ad2527ab41b3932efeda586391ffdc)Limit order: 
image

**Comment by shoom3301** [comment]
@elena-zh fixed: https://github.com/cowprotocol/explorer/pull/268

**Comment by anxolin** [comment]
Yes elena, this is not correct. CowSwap is the correct one. If we see the TX we see the correct value is `0.715205666982927037`: 


https://gnosisscan.io/tx/0xf0f7b1478c8ad98a85d9aed13f04046879ad844e910faffcd5e8a725ae0a161a

**Comment by alfetopito** [comment]
FYI, this change is breaking the unit tests https://github.com/cowprotocol/explorer/actions/runs/3674274430/jobs/6212315141

**Review by elena-zh — APPROVED** [review]
LGTM!

**Pull request merged**
