### PR TITLE
Volume chart and cards layout

### LINKED ISSUE #87: Enhance Volume chart diagram & Cards
Originally reported in https://github.com/cowprotocol/explorer/pull/77#issuecomment-1117769381

Volume chart:

- [x] 1. - Show the accumulated volume as the main label instead of the average as it is right now: DONE in #77
- [x] 2. Update the current `CoW Protocol volume` to reflect the selected period, i.e. `Daily volume`, `Monthly volume`, etc
- [x] 3. Add a Total Volume card
- [x] 4. Add a tooltip with the selected volume and date values
- [x] 5. Make the volume chart bigger so the tooltip is correctly displayed. Make it occupy the whole cards width
- [x] 6. Remove the green/red chart colors which causes confusion. Use a neutral color, the main orange is a good option
- [x] 7. Remove the current x-axis at the current volume value
- [x] 8. Add the x-axis to the hover state, keep the y-axis too

### PR DESCRIPTION
**Pull request by alongoni**
# Summary
**Closes #87**

image
image

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @alongoni , great changes! The page layout looks much0much better now!

However, some nitpicks from my side: 
1. Seems like cards area does not 100% correspond to the Top tokens table area. Can we fix it somehow? 
not 100% aligned
aligned2
2. 'Volume' in the card should be started with an upper-case letter if follow all the rest cards logic: 
volume
3. AFAIU, Total volume card's value is not integrated in this PR. Should I create a task for this? 

Thanks!

**Comment by alfetopito** [comment]
Oh yes, it does look very nice, love how it expands on bigger screens

Small screen view is a bit too wide IMO.
I can understand the graph to remain larger, but I think the cards should shrink like the table

https://user-images.githubusercontent.com/43217/168596744-1f5926fd-4aa1-4782-a033-48ad598a4c72.mov

**Comment by alongoni** [comment]
> I can understand the graph to remain larger, but I think the cards should shrink like the table

Thanks  @alfetopito! We will be working on this issue on #75

**Review by ramirotw — APPROVED** [review]
nice!

**Comment by elena-zh** [comment]
@alongoni , great! 

However, a nitpick: I still can see a mismatch in sections' boarders for some devices. See how sections look like in 'Surface Duo' device
duo 2
surface duo

Could you please fix it? 

Thanks!

**Comment by elena-zh** [comment]
Hey @alongoni ,now the page in small resolutions looks great. 
However, now I see not fully filled in chart in big screen resolutions.
huge screen

 Besides, the page elements are resizing when I change chart periods. See the video: https://watch.screencastify.com/v/XY6AEwulClRA5NMykWzu

**Review by elena-zh — APPROVED** [review]
LGTM now!

**Review by ramirotw — APPROVED** [review]
💅

**Pull request merged**
