### PR TITLE
Release v2.7.0

### PR DESCRIPTION
**Pull request by henrypalacios**
# Release v2.7.0
:rotating_light: :warning: DO NOT SQUASH :warning: :rotating_light:

This version introduces a way to see the interaction of users with the COW protocol through a **node diagram** in the transaction view (🪄 _which we want to improve soon_).

We also fixed a bug in the "_created_" column in the transaction view (👏 thanks to davidbrai who [informed us](https://discord.com/channels/869166959739170836/869170873033166868/958407436820172910) about it)

## Main features:
- Implementation of the batch transaction diagram in the transaction view
- Add a Notification banner to display errors and warnings
- Misc bug fixes and improvements

### Features
01c936c Bump version to 2.7.0
https://github.com/gnosis/gp-ui/commit/0bee3f78fcb3dc5d863c822afa5609bcc19fa287 Implementation of the batch transanction view (https://github.com/gnosis/gp-ui/pull/1061)
https://github.com/gnosis/gp-ui/commit/57e586838b6cfb069a4568582c5c1d5eae55cf1b Use creationDate instead of expirationDate on Tx view (https://github.com/gnosis/gp-ui/pull/1082)
https://github.com/gnosis/gp-ui/commit/1621c24d06e98c35e25dd281f71cd83dd55bedcd Merge pull request https://github.com/gnosis/gp-ui/pull/1080 from gnosis/update-sentry
https://github.com/gnosis/gp-ui/commit/9d488b68079bcf29e7bb547c9c7969aa164773c7 project name fix
https://github.com/gnosis/gp-ui/commit/799c1b79dc5a3493a9653f3a41932cb54e73fab2 update sentry settings
https://github.com/gnosis/gp-ui/commit/514b8f698b95bd764f6c1296f06c7c0f5b823820 Add a Notification component to display errors and warnings (https://github.com/gnosis/gp-ui/pull/992)
https://github.com/gnosis/gp-ui/commit/e31c3773a94ed12bd578d6b2813ee85710e0f858 Adding requests to the tenderly API (https://github.com/gnosis/gp-ui/pull/1057)
https://github.com/gnosis/gp-ui/commit/4956392b92d5fe010b73489f4319271d236e3a60 [Explorer] Home button redirects to the home page based on the network selected (https://github.com/gnosis/gp-ui/pull/1067)
https://github.com/gnosis/gp-ui/commit/c804c175e3e6bd43c0424d2586221b71cf737b29 Fallback to https over websockets for Infura connection in IOS 15 (https://github.com/gnosis/gp-ui/pull/1064)
https://github.com/gnosis/gp-ui/commit/15eabd6bb2dee7a828c3c48cb7bd0a96f9d8fbfa [Explorer] Custom hook for getting explorer data for BlockExplorerLink component when it is not a gpv2 tx (https://github.com/gnosis/gp-ui/pull/930)
https://github.com/gnosis/gp-ui/commit/adc3853c60c9c17ed8e3d9433379330b6920beca reuse useOnClickOutside (https://github.com/gnosis/gp-ui/pull/1013)
https://github.com/gnosis/gp-ui/commit/f5c323ab749869a6172abdd00a3fdcca7cef0d39 [Explorer] Add Github + Etherscan logos to external links (https://github.com/gnosis/gp-ui/pull/1042)
https://github.com/gnosis/gp-ui/commit/25bab0ff299a772109dedb8803347d11145077c2 [Explorer] Remove 'This project is in beta. Use at your own risk' message in footer (https://github.com/gnosis/gp-ui/pull/1036)
https://github.com/gnosis/gp-ui/commit/e7e5b977a553dd7cbc0c47b4296a1cd73b17e68e "Search not found" responsive page (https://github.com/gnosis/gp-ui/pull/1037)
https://github.com/gnosis/gp-ui/commit/3a8378a895aaf052f291d70cc2e75f5fcb9d34e8 Merge pull request https://github.com/gnosis/gp-ui/pull/1038 from gnosis/master

## Dependencies Updates
https://github.com/gnosis/gp-ui/commit/d866d5fca76686db9ce5ff5e4277c979e8c7ed8e Bump Version to 2.7.0-rc.0
https://github.com/gnosis/gp-ui/commit/7ac1d1a4ecae9b5143855d284054f627e20cd050 Bump @sentry/tracing from 6.15.0 to 6.18.0 (https://github.com/gnosis/gp-ui/pull/1059)
https://github.com/gnosis/gp-ui/commit/ccc5dd9e4cd26fb42301ec10093be0fd79c39b2f Bump url-parse from 1.5.3 to 1.5.7 (https://github.com/gnosis/gp-ui/pull/1054)
https://github.com/gnosis/gp-ui/commit/b55ddb5e09c900280ad12f11cf797aca5dc71531 Bump follow-redirects from 1.14.7 to 1.14.8 (https://github.com/gnosis/gp-ui/pull/1049)

### CODE REVIEW

**Comment by henrypalacios** [comment]
Hey @ramirotw and @elena-zh, it would be best to move forward without #41 since I have run into another problem in [PR49](https://github.com/cowprotocol/explorer/pull/49) solving it.

**Comment by elena-zh** [comment]
@henrypalacios , I'm OK to go live now without #41 implemented.

**Review by ramirotw — APPROVED** [review]
🚢

**Comment by anxolin** [comment]
I think is good to merge and release! nice job with this version.

In the release notes, i like is a good summary and that is short. Although, probably nice to mention more things, like how you fixed the createDate since some external people notice, so is nice to see in the changes.


Also, i have some further feedback about the graph. 

1. Can we add images for the DEXs?
image

2. Is it possible to add a link to open Etherscan for the nodes? Like if you want to check out one DEX or user. Maybe with double click, or some other way, cause click maybe makes it difficult to drag and drop.

3. The labeling of DEXes didn't work too well. In this case, its labeling Uniswap as Sushiswap, and for Uniswap is not adding any label: 

https://pr51--gpui.review.gnosisdev.com//rinkeby/tx/0x13afd46b65486466af770441359211bda494c19a3788f188f108b869df0952e3/

image

**Review by anxolin — APPROVED** [review]
This is a great version!

Happy to deploy it. 
I would continue improving this batch representation and making it more findable for the users. Nice job

**Pull request merged**
