### PR TITLE
Adding force-simulation layout algorithm to draw nodes

### LINKED ISSUE #114: Use an algorithm to draw a graph (force-directed)
Part of: https://github.com/cowprotocol/explorer/issues/61

Improve the view of some cases with another **layout** that uses an algorithm of **force-directed** to position `nodes` of a graph.

Selection_574

## Background
Commented on [gnosis/gp-ui/pull/1061](https://github.com/gnosis/gp-ui/pull/1061#issuecomment-1070935367)

### PR DESCRIPTION
**Pull request by henrypalacios**
# Summary

Closes #114 

Adding layout graph selector
Selection_582

## To Test
Open any of the following transactions:
1. [0xaa5d...baf0](https://pr119--explorer.review.gnosisdev.com/tx/0xaa5daa29e997cbf9b6307c707f13c76c3e2cb53ee41b8e85dc3e36e808cbbaf0/?tab=graph)
2. [0x0d6f...ca38](https://pr119--explorer.review.gnosisdev.com/tx/0x0d6f18a97690de9d70cdfe00231ee6baf722a12669f3260fb1faf3d2e25dca38/?tab=graph)
3. [0xd7e3...5894](https://pr119--explorer.review.gnosisdev.com/tx/0xd7e3d38f34efac95b73c2eb1bae9e8c97001cbe06f1e88439a08a7c3bae35894/?tab=graph)
4. [0xc247...ead4](https://pr119--explorer.review.gnosisdev.com/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/?tab=graph)
5. [0xf2a0...d522](https://pr119--explorer.review.gnosisdev.com/tx/0xf2a00ef766bc5caee96cbee8e1842e8ed29ca5059b1a5daa71258d6232d1d522/?tab=graph)

### CODE REVIEW

**Review by elena-zh — CHANGES_REQUESTED** [review]
Hey @henrypalacios , great PR to play with!

Some issues and doubts from my side: 
1. Can we write layout names using upper and lower-case letters? I mean, as a stupid end-user, it was not clear to me what this or that type of diagram means. And when I googled, I found that fcose is actually fCoSE (easies to google it when know a certain name). And klay is KLayout..
2. fCoSE layout always [changes its position](https://watch.screencastify.com/v/FDzJ38AOrFBrMjMly31T) when press on 'reset' button. Maybe instead/or besides of the 'Reset button we should show 'Play' button if it works this way. WDYT?
3. KLayout looks too weird with a lot of overlapped elements, especially for graphs with few nodes
image
image
Maybe we should hide it for such graphs? 

4. In this [transaction ](https://pr119--explorer.review.gnosisdev.com/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/?tab=graph) with klay layout [2 arrows are always blinking ](https://watch.screencastify.com/v/N8k33yb6FA8bUndc3yOb)when press on the Reset button
5. I think it would be nice to 'save' layout selection when s[witch between Graph/Orders tabs ](https://watch.screencastify.com/v/R5D8pg9kwRNEMW54epxk)

Thanks

**Comment by alfetopito** [comment]
First of all, very nice. It's very useful for some more unusual batches like the ones you shared.

Now, regarding Elena's points:

`2`. I'm not found of `play` as it indicates to me that it should play something, like a video. I would prefer `re-arrange` instead

`3`. Agree, looks weird, but I don't think we have enough data, and might not be worth the effort to try and identify when it should be hidden. I'd leave it up to the user to pick a different layout if they chose to

`5` Out of the scope of this task, and might not make sense, as every layout might fit better a different type of settlement. I think the grid is the best use case for the majority of cases and as it's already the default.


And some points from me:

`L1`: Not very found of the animation on load. Can it be disabled?
`L2`: The table seems to 'jump' when switching between graph and list. That's not in the video, but the jump is because the graph causes the browser to have a scroll bar, which is removed when I go to the list.
Even on one batch where [it has a scroll bar](https://pr119--explorer.review.gnosisdev.com/tx/0xf2a00ef766bc5caee96cbee8e1842e8ed29ca5059b1a5daa71258d6232d1d522/?tab=orders) there's some jumping 

https://user-images.githubusercontent.com/43217/174858130-29ac355c-69b7-4f14-9800-423d2aa38ef7.mov

`L3`: I understand the layouts match the algorithms, but does it make sense from a user point of view? I don't have a good suggestion here, just find it not relevant and would prefer a name more meaningful, like `grid`.

**Review by alfetopito — APPROVED** [review]
❤️

**Comment by elena-zh** [comment]
Hey @henrypalacios , great changes! 
I have found some low-prio UI issues, but reported them as separate tasks in order to fix it later: 
 - issues with Reset button will b solved by disabling it for a default BV view https://github.com/cowprotocol/explorer/issues/101#issuecomment-1162948239
 - https://github.com/cowprotocol/explorer/issues/134
 - I think, it would be nice to place a layout button to another place in a mobile view https://github.com/cowprotocol/explorer/issues/135 . But is the current position looks good to all the rest team members, this issue might be closed. 

Thanks

**Review by elena-zh — APPROVED** [review]

**Review by ramirotw — APPROVED** [review]
StandingOvationGIF

**Pull request merged**
